version: '3.1'
services:
  stub-sp:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${STUB_SP_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
    volumes:
      - ../EIDAS-SP/target/SP.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-SP/target/SP:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - stub-connector
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "STUB_SP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubSpKeystore.jks"
      - "STUB_SP_KEYSTORE_PASSWORD=Password"
      - "STUB_SP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub SP Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_SP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=41573ab34ef7100cb77e4c5aca551826cf86a1e9"
      - "STUB_SP_SIGNING_CERTIFICATE_DISTINGUSHED_NAME=CN=Test Stub SP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_SP_SIGNING_CERTIFICATE_SERIAL_NUMBER=123f7141d99aa3b6ad31211dabb9ca7abdc08b5d"

      - "SP_URL=http://stub-sp:${DEFAULT_TOMCAT_PORT}"
      - "EXT_SP_URL=http://localhost:${STUB_SP_HTTP_PORT}"
      - "SERVICE_METADATA_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "CONNECTOR_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}"
      - "EXT_CONNECTOR_URL=http://localhost:${CONNECTOR_NODE_HTTP_PORT}"
      - "CONNECTOR_METADATA_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"

      - "NODE_METADATA_SSO_LOCATION="
      - "IDP_URL="
      - "IDP_SSO_URL="
      - "PROXY_URL="
      - "EXT_IDP_URL="
      - "EXT_PROXY_URL="

      - "COUNTRY_1_CODE=NL"
      - "COUNTRY_1_NAME=The Netherlands"
      - "COUNTRY_1_PROXY_URL=http://proxy-node-1:${DEFAULT_TOMCAT_PORT}"
      - "COUNTRY_1_PROXY_METADATA_URL=http://proxy-node-1${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "COUNTRY_2_CODE=ES"
      - "COUNTRY_2_NAME=Spain"
      - "COUNTRY_2_PROXY_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}"
      - "COUNTRY_2_PROXY_METADATA_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

  connector-node:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${CONNECTOR_NODE_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
    volumes:
      - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - stub-connector
      - connector-proxy1
      - connector-proxy2
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/connectorNodeKeystore.jks"
      - "NODE_KEYSTORE_PASSWORD=Password"
      - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Connector Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Connector Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=1dcfdeedc8983a5f13f2338e0814b6e47090b3d7"
      - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=56520de46a76cb6ad7b9c238dd253d88904da9d8"

      - "SP_URL=http://stub-sp:${DEFAULT_TOMCAT_PORT}"
      - "EXT_SP_URL=http://localhost:${STUB_SP_HTTP_PORT}"
      - "SERVICE_METADATA_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "CONNECTOR_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}"
      - "EXT_CONNECTOR_URL=http://localhost:${CONNECTOR_NODE_HTTP_PORT}"

      - "NODE_METADATA_SSO_LOCATION=http://localhost:${CONNECTOR_NODE_HTTP_PORT}/ColleagueRequest"

      - "IDP_URL="
      - "IDP_SSO_URL="
      - "PROXY_URL="                #needs to be set for connector? line 273 of eidas.xml
      - "EXT_IDP_URL="
      - "EXT_PROXY_URL="

      - "COUNTRY_1_CODE=NL"
      - "COUNTRY_1_NAME=The Netherlands"
      - "COUNTRY_1_PROXY_URL=http://proxy-node-1:${DEFAULT_TOMCAT_PORT}"
      - "COUNTRY_1_PROXY_METADATA_URL=http://proxy-node-1${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "COUNTRY_2_CODE=ES"
      - "COUNTRY_2_NAME=Spain"
      - "COUNTRY_2_PROXY_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}"
      - "COUNTRY_2_PROXY_METADATA_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

  proxy-node-1:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${COUNTRY_1_PROXY_NODE_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
      #- "${EXPOSED_TOMCAT_DEBUG_PORT}:${DEFAULT_TOMCAT_JPDA_PORT}"
    volumes:
      - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - connector-proxy1
      - proxy1-idp1
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/proxyNodeKeystore.jks"
      - "NODE_KEYSTORE_PASSWORD=Password"
      - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=6641716bee633fb618dbd85b7d41e63b62046c2d"
      - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=203b6cb0714922c675e08606187e75c4c4457a1c"

      - "SERVICE_METADATA_URL=http://proxy-node-1:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "CONNECTOR_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}"
      - "PROXY_URL=http://proxy-node-1:${DEFAULT_TOMCAT_PORT}"
      - "EXT_PROXY_URL=http://localhost:${COUNTRY_1_PROXY_NODE_HTTP_PORT}"
      - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_1_PROXY_NODE_HTTP_PORT}/ColleagueRequest"
      - "IDP_URL=http://stub-idp-1:${DEFAULT_TOMCAT_PORT}"
      - "IDP_SSO_URL=http://stub-idp-1:${DEFAULT_TOMCAT_PORT}"
      - "EXT_IDP_URL=http://localhost:${COUNTRY_1_STUB_IDP_HTTP_PORT}"

      - "EXT_CONNECTOR_URL="
      - "EXT_SP_URL="
      - "SP_URL="

      - "COUNTRY_1_CODE="
      - "COUNTRY_1_NAME="
      - "COUNTRY_1_PROXY_URL="
      - "COUNTRY_2_CODE="
      - "COUNTRY_2_NAME="
      - "COUNTRY_2_PROXY_URL="
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

  proxy-node-2:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${COUNTRY_2_PROXY_NODE_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
    volumes:
      - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - connector-proxy2
      - proxy2-idp2
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/proxyNodeKeystore.jks"
      - "NODE_KEYSTORE_PASSWORD=Password"
      - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=6641716bee633fb618dbd85b7d41e63b62046c2d"
      - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=203b6cb0714922c675e08606187e75c4c4457a1c"

      - "SERVICE_METADATA_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}/ServiceMetadata"
      - "CONNECTOR_URL=http://connector-node:${DEFAULT_TOMCAT_PORT}"
      - "PROXY_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}"
      - "EXT_PROXY_URL=http://localhost:${COUNTRY_2_PROXY_NODE_HTTP_PORT}"
      - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_2_PROXY_NODE_HTTP_PORT}/ColleagueRequest"
      - "IDP_URL=http://stub-idp-2:${DEFAULT_TOMCAT_PORT}"
      - "IDP_SSO_URL=http://stub-idp-2:${DEFAULT_TOMCAT_PORT}"
      - "EXT_IDP_URL=http://localhost:${COUNTRY_2_STUB_IDP_HTTP_PORT}"

      - "EXT_CONNECTOR_URL="
      - "EXT_SP_URL="
      - "SP_URL="

      - "COUNTRY_1_CODE="
      - "COUNTRY_1_NAME="
      - "COUNTRY_1_PROXY_URL="
      - "COUNTRY_2_CODE="
      - "COUNTRY_2_NAME="
      - "COUNTRY_2_PROXY_URL="
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

  stub-idp-1:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${COUNTRY_1_STUB_IDP_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
    volumes:
      - ../EIDAS-IdP-1.0/target/IdP.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-IdP-1.0/target/IdP:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - proxy1-idp1
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "STUB_IDP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubIdpKeystore.jks"
      - "STUB_IDP_KEYSTORE_PASSWORD=Password"
      - "STUB_IDP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Encryption 20161031, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_IDP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=723c0f7f4b45dea5296e53f565535174d0df5218"
      - "STUB_IDP_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_IDP_SIGNING_CERTIFICATE_SERIAL_NUMBER=5ae2153c3f9a99824df394abd65f9e1e8ca53365"

      - "PROXY_URL=http://proxy-node-1:${DEFAULT_TOMCAT_PORT}"
      - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_1_STUB_IDP_HTTP_PORT}/ColleagueRequest"
      - "IDP_URL=http://stub-idp-1:${DEFAULT_TOMCAT_PORT}"
      - "IDP_SSO_URL=http://stub-idp-1:${DEFAULT_TOMCAT_PORT}"
      - "EXT_CONNECTOR_URL="
      - "EXT_SP_URL="
      - "SP_URL="
      - "EXT_PROXY_URL="

      - "IDP_COUNTRY_CODE=NL"

      - "COUNTRY_1_CODE="
      - "COUNTRY_1_NAME="
      - "COUNTRY_1_PROXY_URL="
      - "COUNTRY_2_CODE="
      - "COUNTRY_2_NAME="
      - "COUNTRY_2_PROXY_URL="
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

  stub-idp-2:
    image: eidas/tomcat:8.5.11-jre8-alpine-UnlimitedJCEPolicyJDK8
    ports:
      - "${COUNTRY_2_STUB_IDP_HTTP_PORT}:${DEFAULT_TOMCAT_PORT}"
    volumes:
      - ../EIDAS-IdP-1.0/target/IdP.war:/usr/local/tomcat/webapps/ROOT.war
      - ../EIDAS-IdP-1.0/target/IdP:/usr/local/tomcat/webapps/ROOT
      - ../EIDAS-Config:/usr/local/share/eidas
    networks:
      - proxy2-idp2
    environment:
      - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
      - "STUB_IDP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubIdpKeystore.jks"
      - "STUB_IDP_KEYSTORE_PASSWORD=Password"
      - "STUB_IDP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Encryption 20161031, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_IDP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=723c0f7f4b45dea5296e53f565535174d0df5218"
      - "STUB_IDP_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
      - "STUB_IDP_SIGNING_CERTIFICATE_SERIAL_NUMBER=5ae2153c3f9a99824df394abd65f9e1e8ca53365"

      - "PROXY_URL=http://proxy-node-2:${DEFAULT_TOMCAT_PORT}"
      - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_2_STUB_IDP_HTTP_PORT}/ColleagueRequest"
      - "IDP_URL=http://stub-idp-2:${DEFAULT_TOMCAT_PORT}"
      - "IDP_SSO_URL=http://stub-idp-2:${DEFAULT_TOMCAT_PORT}"
      - "EXT_CONNECTOR_URL="
      - "EXT_SP_URL="
      - "SP_URL="
      - "EXT_PROXY_URL="

      - "IDP_COUNTRY_CODE=ES"

      - "COUNTRY_1_CODE="
      - "COUNTRY_1_NAME="
      - "COUNTRY_1_PROXY_URL="
      - "COUNTRY_2_CODE="
      - "COUNTRY_2_NAME="
      - "COUNTRY_2_PROXY_URL="
      - "COUNTRY_3_CODE="
      - "COUNTRY_3_NAME="
      - "COUNTRY_3_PROXY_URL="
      - "COUNTRY_4_CODE="
      - "COUNTRY_4_NAME="
      - "COUNTRY_4_PROXY_URL="
      - "COUNTRY_5_CODE="
      - "COUNTRY_5_NAME="
      - "COUNTRY_5_PROXY_URL="
      - "COUNTRY_6_CODE="
      - "COUNTRY_6_NAME="
      - "COUNTRY_6_PROXY_URL="
      - "COUNTRY_7_CODE="
      - "COUNTRY_7_NAME="
      - "COUNTRY_7_PROXY_URL="

networks:
  stub-connector:
  connector-proxy1:
  connector-proxy2:
  proxy1-idp1:
  proxy2-idp2:
